# Generated by Django 5.0.1 on 2024-02-10 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tombstone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tombstone_id",
                    models.IntegerField(blank=True, verbose_name="ID надгробия"),
                ),
                (
                    "create_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "user_id",
                    models.IntegerField(blank=True, verbose_name="ID пользователя"),
                ),
                (
                    "user_role",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Роль пользователя",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Название компании",
                    ),
                ),
                (
                    "birth_year",
                    models.DateField(
                        blank=True, null=True, verbose_name="Год создания"
                    ),
                ),
                (
                    "death_year",
                    models.DateField(blank=True, null=True, verbose_name="Год смерти"),
                ),
                (
                    "alternate_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Алльтернативное название",
                    ),
                ),
                (
                    "link",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Ссылка на компанию",
                    ),
                ),
                (
                    "characteristic",
                    models.TextField(
                        blank=True, null=True, verbose_name="Характеристики компании"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание компании"
                    ),
                ),
                (
                    "death_cause",
                    models.TextField(
                        blank=True, null=True, verbose_name="Причина смерти компании"
                    ),
                ),
                (
                    "count_employee",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Количество сотрудников"
                    ),
                ),
                (
                    "revenue",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Доход компании"
                    ),
                ),
                (
                    "score_company",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Счет компании"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Имя пользователя",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Фамилия пользователя",
                    ),
                ),
                (
                    "on_admin",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Является ли админом"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="property.tombstone",
                    ),
                ),
            ],
        ),
    ]
